### ISSUE TITLE
Clickable links that show the marked selection in the main list

### ISSUE THREAD

**Issue by davidgbergling** [Lundalogik/LimeBootstrapAppStore#12]
A great enhancement of the helpdesk statistics app would be to be able to clik onthe selections eg "Mina Öppna ärenden" and show the selectet helpdesk cases in the main list. 

I believe much of the code could already is written in the bussiness funnel app.

![helpdeskstatistics](https://cloud.githubusercontent.com/assets/7644433/3026770/103b3fb8-e01a-11e3-934e-f007a874fabd.png)

**Comment by justFredster** [comment]
Have added this as an improvement idea for when someone will modernize the add-on "helpdeskstatics" (sic!). Closing this issue therefore.
