### ISSUE TITLE
Better error message when having been logged out

### ISSUE THREAD

**Issue by tomaseketorp** [Lundalogik/LimeBootstrapAppStore#20]
If you leave LIME open, you will eventually be logged out after some time. Then you get an error message "Filter or class not found" when you should, preferably, not get an error message at all (since LIME will tell you that you've been logged out when you try to use it) or an error message saying, like "You've been logged out. Log back in."

**Comment by andreasastrom** [comment]
Sounds like a good idea! We will try to look at it

**Comment by tomaseketorp** [comment]
I thought I commented on the app InfoTile. But this sees to be for AppStore. Sorry for the confusion.

**Comment by justFredster** [comment]
This should be added for all apps that retrieve data on their own on a schedule.

**Comment by TommyLindh2** [comment]
This is already fixed for the infotiles app.
It gives no error when the error code is a few hard coded ones.
But also the Auto-reload function have been disabled for this app.

I don't think that it is a good idea to schedule it for this app.

**Comment by justFredster** [comment]
Great @TommyLindh2 ! I close this issue and add the error code exceptions thing to my list of fixes needed in different apps. :)
