### ISSUE TITLE
Garcon gives error when having been automatically logged out

### ISSUE THREAD

**Issue by justFredster** [Lundalogik/LimeBootstrapAppStore#22]
If you leave your Lime and come back 24h+ later, Garcon will have given an error message due to the automatic log out. This should be taken care of by making an exception for that error code in the ErrorHandler of the VBA sub. The error code and VBA sub is found below.

---
## Lime

Your session has been ended due to inactivity.

Källa: Garcon.FetchFiltersXML

**Comment by LarsCJensen** [comment]
The error might be caused by some interruptions in our own environment. This issue should be confirmed.

**Comment by justFredster** [comment]
It is definitely confirmed since the report is almost a year old now and I get the same error message repeatedly from our own Lime, where there is other things from the VBA code giving the same error, for example, the time report reminder and the charging gauge.

**Comment by justFredster** [comment]
@TommyLindh2 See the above error code. It is not part of the error codes to ignore in the error handler in the sub FetchFiltersXML. Is there a reason for that or should it be added?

**Comment by TommyLindh2** [comment]
It should be added if it's missing

**Comment by justFredster** [comment]
@TommyLindh2 I have added it now.
