### ISSUE TITLE
XML fails when you activate departments, but the coworker has no departments connected

### ISSUE THREAD

**Issue by anhuynhh** [Lundalogik/LimeBootstrapAppStore#58]
Code crashes in Garcon.FetchFiltersXML

Throws XML failed miserably error.

Dirty fixed it by checking
` If bDepartmentoptionenabled **And Not IsBull(Activeuser.record.value(sDepartmentFieldName)** `
but then the user need to relog if they get a department connected for Lime to fetch new data.

**Comment by justFredster** [comment]
@TommyLindh2 Can you have a look at this?

**Comment by TommyLindh2** [comment]
I'll look into it!

**Comment by TommyLindh2** [comment]
@justFredster Now it's fixed.

**Comment by justFredster** [comment]
Closing this issue since @TommyLindh2 has fixed it.
